### ISSUE TITLE
Location not recognized

### ISSUE THREAD

**Issue by javierquevedo** [zverok/wheretz#4]
Some locations are not recognized.
Here is an example.
WhereTZ.get(43.6605555555556, 7.2175)  #=> nil

If you place such lat long on a map you will clearly see that it lands right on top of Niece's Airport, France.
Such Airport is on the coast, which might explain it. I imagine that may have something to do with it.

**Comment by zverok** [comment]
Yes, point occures slightly outside any of polygons. Fixed it in 0.0.2 with pretty non-elegant solution (just check distance to all candidate polygon points and select closest one). It is slow (0.5s instead of 0.1s) edge case, but pretty rare, I assume.

```ruby
WhereTZ.get(43.6605555555556, 7.2175) # => #<TZInfo::DataTimezone: Europe/Paris> 
```

**Comment by javierquevedo** [comment]
Is the fix committed to the master?
Thanks for you swift reaction.

**Comment by zverok** [comment]
Yep, here it is: https://github.com/zverok/wheretz/commit/a69eee647fe456b22ae8959c4c48a83352f52e56

And new gem version (0.0.2) should be already on Rubygems.

**Comment by javierquevedo** [comment]
Fantastic.
I will let you know if I encounter any other issues.

Thanks again!
