### ISSUE TITLE
NoMethodError:  undefined method `y' for false:FalseClass

### ISSUE THREAD

**Issue by jotolo** [zverok/wheretz#5]
```
@timezone_id ||= WhereTZ.lookup(x.latitude, x.longitude) ||
                        session_params[:timezone_id]
     
     NoMethodError:
       undefined method `y' for false:FalseClass
```

This is happening randomly in some code I use everyday.
Any ideas?

**Comment by zverok** [comment]
Can you please provide the full error backtrace?

**Comment by jotolo** [comment]
There is no error backtrace. The rest is from my code in my application because I'm getting the error from my specs :( I know this is not helpful, sorry.

**Comment by zverok** [comment]
Somehow it receives `false` somewhere deep in the internals, where other data expected. I don't see anything that uses `y` method in the library's code, so it is either some underlying libraries, or your client code. Backtrace of the error (what exact chain of calls lead to it) could really help.

**Comment by jotolo** [comment]
I'm going to check what `longitude` and `latitude` is passing as argument. I will let you know. Thank you!

**Comment by sfate** [comment]
I suppose it goes from `GeoRuby` lib as there is underlying methods (with `y` variable definition) which this lib is using.

**Comment by jotolo** [comment]
@zverok Could you please, check @sfate comment?

**Comment by zverok** [comment]
@jotolo I really need more information for debugging, some reproducible test case or at least detailed backtrace to the place where the error really happens. It is really hard to guess otherwise

**Comment by jotolo** [comment]
@zverok I've got some information for you. It's useful. It's kinda the same issue.
```
from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:49:in `lookup'
       11: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:86:in `lookup_geo'
       10: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:86:in `select'
        9: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:87:in `block in lookup_geo'
        8: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:87:in `any?'
        7: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/wheretz-0.0.2/lib/wheretz.rb:87:in `block (2 levels) in lookup_geo'
        6: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/polygon.rb:97:in `contains_point?'
        5: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/polygon.rb:97:in `select'
        4: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/polygon.rb:97:in `block in contains_point?'
        3: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/linear_ring.rb:26:in `contains_point?'
        2: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/linear_ring.rb:26:in `select'
        1: from /var/www/backend/vendor/bundle/ruby/2.5.0/gems/georuby-2.5.2/lib/geo_ruby/simple_features/linear_ring.rb:27:in `block in contains_point?'
NoMethodError (undefined method `>' for nil:NilClass)
```

**Comment by jotolo** [comment]
[PR created](https://github.com/nofxx/georuby/pull/54) to fix this issue in georuby library.

**Comment by zverok** [comment]
@jotolo I am not sure it is a bug in GeoRuby per se... Maybe a bug in data. If I understand your PR correctly, that happens that in some of geometry features loaded from WhereTZ source files, there is some point that has `x` or `y` as `nil`, right?.. I believe it is either of two:
1. Bug in the data (could be probably spotted by GeoRuby on _loading_, but not necessarily)
2. Bug in GeoRuby data _loading_ (it loads perfectly sane data in a way that it now has some `nil`s)

Either way:
* it will be helpful (for WhereTZ or GeoRuby) if you could debug output (maybe by changing locally `WhereTZ#inside_multipolygon?` method code) which exact multypoligon with which exact point causes this behavior
* if GeoRuby requires a fix, it probably is on _multipolygon loading_, not on `contains_point?`, to make sure neither of its `@points` has `nil`s instead of coordinates, but before that it definitely needs to be caught, _when_ they can have it.

**Comment by jotolo** [comment]
@zverok Sorry about the late reply. In this [log file](https://github.com/zverok/wheretz/files/3519327/wheretz.log) you can find an example of the multipolygon and a point causing the issue. Also, the small backtrace was added to the file. 
Please, let me know if you find the issue here. It's a strange issue regarding to some `nil` values.
Thanks in advance.

**Comment by zverok** [comment]
@jotolo Sorry about me replying lately myself, but I still don't quite get it :( Your logs say the problematic point is:
```
#<GeoRuby::SimpleFeatures::Point:0x0000562778bc1358 @srid=4326, @with_z=false, @with_m=false, @y=14.282239542427845, @x=-82.84276949121094, @z=0.0, @m=0.0>
```
(which means lat `-82.84276949121094`, lng `14.282239542427845`)
But 
```ruby
WhereTZ.lookup(-82.84276949121094, 14.282239542427845)
# => "Antarctica/Troll" 
```
It is really hard to hunt for the bug without reproducible case :(

**Comment by jotolo** [comment]
@zverok Thanks for checking this out. It turns out this issue was caused by random and invalid data in this case.
If someone else has issues like this one in the future make sure you're using correct longitude and latitude values.
